/**
 * Cursores em pixel art, no espírito dos jogos de apontar e clicar.
 * Contorno no índice do fundo e miolo creme: lê na página escura e no cartão-postal claro.
 * `ponta` é o ponto ativo, em pixels do sprite — onde o clique acontece.
 */
export const CURSORES = {
  seta: {
    ponta: [0, 0],
    desenho: [
      "F..........",
      "FF.........",
      "FCF........",
      "FCCF.......",
      "FCCCF......",
      "FCCCCF.....",
      "FCCCCCF....",
      "FCCCCCCF...",
      "FCCCCCCCF..",
      "FCCCCCCCCF.",
      "FCCCCCFFFFF",
      "FCCFCCF....",
      "FCF.FCCF...",
      "FF..FCCF...",
      "F....FCCF..",
      "......FF...",
    ],
  },
  mao: {
    ponta: [6, 0],
    desenho: [
      "......FF........",
      ".....FCCF.......",
      ".....FCCF.......",
      ".....FCCF.......",
      ".....FCCFFF.....",
      ".....FCCFCCFFF..",
      ".....FCCFCCFCCF.",
      "..FF.FCCFCCFCCF.",
      ".FCCFFCCFCCFCCF.",
      ".FCCFCCCCCCCCBF.",
      "..FCCCCCCCCCCBF.",
      "..FCCCCCCCCCCBF.",
      "...FCCCCCCCCBF..",
      "...FCCCCCCCCBF..",
      "....FCCCCCCBF...",
      "....FFFFFFFFF...",
    ],
  },
  /** A mão no clique: o indicador afunda dois pixels, a ponta continua no mesmo lugar. */
  "mao-apertando": {
    ponta: [6, 0],
    desenho: [
      "................",
      "................",
      "......FF........",
      ".....FCCF.......",
      ".....FCCFFF.....",
      ".....FCCFCCFFF..",
      ".....FCCFCCFCCF.",
      "..FF.FCCFCCFCCF.",
      ".FCCFFCCFCCFCCF.",
      ".FCCFCCCCCCCCBF.",
      "..FCCCCCCCCCCBF.",
      "..FCCCCCCCCCCBF.",
      "...FCCCCCCCCBF..",
      "...FCCCCCCCCBF..",
      "....FCCCCCCBF...",
      "....FFFFFFFFF...",
    ],
  },
  /** Examinar: objetos da prateleira e espaços do inventário. */
  lupa: {
    ponta: [5, 5],
    desenho: [
      "...FFFFF........",
      "..FCCCCCF.......",
      ".FCBBBBBCF......",
      "FCBCCBBBBCF.....",
      "FCBCBBBBBCF.....",
      "FCBBBBBBBCF.....",
      "FCBBBBBBBCF.....",
      "FCBBBBBBBCF.....",
      ".FCBBBBBCF......",
      "..FCCCCCFFF.....",
      "...FFFFFFAAF....",
      ".........FAAF...",
      "..........FAAF..",
      "...........FAAF.",
      "............FAAF",
      ".............FF.",
    ],
  },
  texto: {
    ponta: [3, 8],
    desenho: [
      "FFFFFFF",
      "FCCCCCF",
      "FFFCFFF",
      "..FCF..",
      "..FCF..",
      "..FCF..",
      "..FCF..",
      "..FCF..",
      "..FCF..",
      "..FCF..",
      "..FCF..",
      "..FCF..",
      "..FCF..",
      "FFFCFFF",
      "FCCCCCF",
      "FFFFFFF",
    ],
  },
} as const satisfies Record<string, { ponta: readonly [number, number]; desenho: readonly string[] }>;

export type NomeCursor = keyof typeof CURSORES;
